[project]
name = "longterm-memory-langmem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-ollama>=0.3.8",
    "langmem>=0.0.29",
    "numpy>=2.3.3",
]
